import {PHASES,PLANTS,ANIMALS,FOOTPRINTS,EQUIPMENT,GLOBALS,CULTURES,CONTRACTS,RECIPES,OFFLINE_CAP} from './content.mjs';
import {initialState,act,advance,tankView,tankById,facility,phaseNeeds,goal,orderNeeds,cultureView,availableFish,templatePrice,encodeSave,decodeSave} from './engine.mjs';
import {SaveStore,SAVE_KEY} from './persistence.mjs';
import {loadArt,renderAquarium} from './art.mjs';

const $=id=>document.getElementById(id);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=n=>'$'+(n/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const qty=n=>(n/1000).toFixed(1);
const duration=n=>n>=3600?`${Math.floor(n/3600)}h ${Math.floor(n%3600/60)}m`:n>=60?`${Math.floor(n/60)}m ${Math.ceil(n%60)}s`:`${Math.ceil(n)}s`;
const store=new SaveStore();
let loaded=store.load(), state=loaded?.state||initialState(), selected=state.tanks[0].id, tab='room', marketTab='contracts', speed=1;
let busy=false,lastWall=Date.now(),lastSave=0,lastRender=0,artKey='',artElement=null,toastTimer,audioContext,navKey='';
store.claim();
const button=(label,cmd,disabled=false,primary=false)=>`<button class="button ${primary?'primary':''}" data-command="${esc(JSON.stringify(cmd))}" ${disabled?'disabled':''}>${label}</button>`;
const action=(label,name,extra='',primary=false)=>`<button class="button ${primary?'primary':''}" data-action="${name}" ${extra}>${label}</button>`;
const progress=(value,max,label='')=>`<div class="track" role="progressbar" aria-label="${esc(label||'Progress')}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${Math.min(max,value).toFixed(1)}"><span style="width:${Math.max(0,Math.min(100,value/max*100))}%"></span></div>`;
const select=(id,label,options,current)=>`<label class="field" for="${id}"><span>${label}</span><select id="${id}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(current)?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),5000);}
function sound(){if(!state.settings.sound)return;try{audioContext??=new AudioContext();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.type='sine';oscillator.frequency.setValueAtTime(523,audioContext.currentTime);oscillator.frequency.exponentialRampToValueAtTime(784,audioContext.currentTime+.09);gain.gain.setValueAtTime(.035,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.22);oscillator.start();oscillator.stop(audioContext.currentTime+.23);}catch{}}
function save(explicit=false){if(busy)return;const ok=store.save(state,Date.now(),explicit);lastSave=Date.now();$('save-status').textContent=ok?'Saved in this browser · export a copy in Settings':store.error||'Another tab is running this room.';}
function tick(){const now=Date.now();if(document.hidden||busy)return;if(!store.readOnly){const elapsed=Math.max(0,(now-lastWall)/1000);if(elapsed>30){lastWall=now;catchUp(Math.min(elapsed,OFFLINE_CAP));return;}const phase=state.phase,ended=state.finale.completedAt;state=advance(state,elapsed*speed);if(phase!==state.phase)toast(`Chapter ${state.phase} · ${PHASES[state.phase-1][0]}`);if(ended===null&&state.finale.completedAt!==null){tab='workshop';toast('Your independent fish room is complete.');}if(now-lastRender>1000)render(false);if(now-lastSave>5000)save();}lastWall=now;}
async function catchUp(seconds){if(!seconds||store.readOnly||busy)return;busy=true;document.body.classList.add('catching-up');notice(`Your room is catching up on ${duration(seconds)} away…`);try{state=await new Promise((resolve,reject)=>{const worker=new Worker('./worker.mjs',{type:'module'});worker.onmessage=event=>{worker.terminate();event.data.error?reject(new Error(event.data.error)):resolve(event.data.state);};worker.onerror=event=>{worker.terminate();reject(new Error(event.message));};worker.postMessage({state,seconds});});toast(`${duration(seconds)} of production credited. Protected stock stayed in the room.`);}catch(error){notice(`Catch-up stopped: ${error.message}`,true);}finally{busy=false;lastWall=Date.now();document.body.classList.remove('catching-up');save();render();}}
function notice(message,warning=false){$('notice').hidden=!message;$('notice').textContent=message||'';$('notice').className='notice'+(warning?' warning':'');}
function dispatch(command){if(busy)return toast('Finishing the away-time calculation.');if(store.readOnly)return toast('This room is active in another tab. Take over in Settings.');const result=act(state,command);if(!result.ok)return toast(result.message);state=result.state;save();sound();render();if(command.type==='buyTank'||command.type==='template'){selected=state.tanks.at(-1).id;tab='room';render();}if(['harvest','sellPlants','sellFish','stock','equipment','global','order','selection','culture'].includes(command.type))toast(({harvest:'Cuttings collected. Their roots remain protected.',sellPlants:'Plant surplus sold.',sellFish:'Mature juveniles sold. Breeders stay home.',stock:'The new residents are settling in.',equipment:'Installed. A little more room to grow.',global:'Your room has a new capability.',order:'Ingredients reserved. Delivery is under way.',selection:'Selection begun. Raise two supported cohorts.',culture:'The starter culture is in its vessel.'})[command.type]);}
function checklist(){return `<ul class="checklist">${phaseNeeds(state).map(([done,label])=>`<li class="${done?'done':''}"><span class="checkmark">${done?'✓':'○'}</span>${esc(label)}</li>`).join('')}</ul>`;}
function globals(){return Object.entries(GLOBALS).filter(([k,d])=>!state.unlocks[k]&&d.phase<=state.phase).map(([k,d])=>`<div class="catalog-item"><h3>${d.name}</h3><p>${d.note}</p>${button(`${cash(d.cost)} · Install`,{type:'global',key:k},state.cash<d.cost)}</div>`).join('');}
function queue(){return state.jobs.length?`<div class="queue">${state.jobs.map(j=>`<article><div class="job-head"><strong>${esc(j.name)}</strong><span>${duration(j.remaining)}</span></div>${progress(j.duration-j.remaining,j.duration,j.name)}<div class="job-foot"><span>${j.price?`${cash(j.price)} on delivery · `:''}${j.escrow?.fish.length?'Reserved fish still occupy their home tanks.':'Ingredients are held for this job.'}</span>${button('Cancel & return',{type:'cancel',id:j.id})}</div></article>`).join('')}</div>`:'<p class="meta">The workbench is clear. Nothing is waiting in a queue.</p>';}
function room(){const t=tankById(state,selected)||state.tanks[0],v=tankView(state,t),f=facility(state),a=ANIMALS[t.species];selected=t.id;
  const choices=Object.entries(ANIMALS).filter(([,d])=>d.phase<=state.phase&&(!t.species||d.utility||d===a));
  const routeChoices=[['','No transfer'],...state.tanks.filter(x=>x.id!==t.id).map(x=>[x.id,x.name])];
  return `<div class="tank-tabs" role="group" aria-label="Your aquariums">${state.tanks.map(x=>`<button class="tank-tab ${x.id===selected?'active':''}" data-tank="${x.id}" aria-pressed="${x.id===selected}"><span class="status-dot"></span>${esc(x.name)}<small>${FOOTPRINTS[x.footprint].short} · ${ANIMALS[x.species]?.name||'Planted'}</small></button>`).join('')}</div><div class="room-layout"><div><section class="aquarium"><div class="tank-title"><div><p class="eyebrow">${FOOTPRINTS[t.footprint].name} · ${PLANTS[t.crop].name}</p><h2 class="tank-name">${esc(t.name)}</h2></div><div class="actions">${action('Rename','rename')}${action('Reconfigure','reconfigure')}</div></div><div class="tank-art" id="tank-art"></div><div class="aquarium-caption"><span class="status-dot"></span>${esc(v.blocker)}${t.ready?` · ${duration(t.ready)}`:''}</div><div class="growth-row"><div class="growth-title"><strong>${qty(t.biomass)} plant biomass</strong><span class="rate">up to +${v.potential.toFixed(2)}/min</span></div>${progress(t.biomass,v.plantCap,'Living plant biomass')}<div class="track-label"><span>${qty(t.reserve)} protected · ${qty(state.inventory.plants[t.crop])} loose cuttings</span><span>${qty(v.plantCap)} capacity</span></div><div class="actions">${button('Trim surplus',{type:'harvest',id:t.id},t.biomass-t.reserve<1000,true)}${button('Sell cuttings · '+cash(Math.floor(state.inventory.plants[t.crop]/1000*PLANTS[t.crop].price)),{type:'sellPlants',key:t.crop},!state.inventory.plants[t.crop])}${button('Replant 1 cutting',{type:'replant',id:t.id},state.inventory.plants[t.crop]<1000||t.biomass+1000>v.plantCap)}</div></div><div class="growth-row"><div class="growth-title"><strong>${a?a.name:'Your first breeding group'}</strong><span class="rate">${v.load.toFixed(1)} / ${v.capacity.toFixed(1)} safe load</span></div>${progress(v.load,v.capacity,'Livestock capacity')}<div class="stock-chip">${t.breeders} protected breeders · ${v.fry} growing · ${v.young} sale-ready · ${v.promised} reserved</div>${a?`<p class="meta">${v.nextMature!==null?`Next mature cohort in ${duration(v.nextMature)}. `:''}${t.breeders?`Birth cycle ${duration(v.pulseEvery)}; ${duration(Math.max(0,v.pulseEvery-t.pulse))} until ready.`:'Receiving tank: move mature fish here to establish a breeding line.'}</p><div class="actions">${button('Sell grown surplus',{type:'sellFish',id:t.id},!v.young,true)}${button('Retain a breeding group',{type:'retain',id:t.id},v.young<a.group)}${state.phase>=2?button('List surplus · +35%, 3 min',{type:'market',id:t.id,key:'fish'},!v.young):''}</div>`:'<p class="meta">Trim and sell your first cuttings. Install the $8 sponge, then add a $12 guppy group. Plant income funds the first fish.</p>'}</div></section>
  <div class="tank-controls"><section class="block"><p class="eyebrow">LIVING STOCK</p><h2>Choose what grows here</h2>${select('stock-choice','New residents',choices.map(([k,d])=>[k,`${d.name} · ${d.utility?'companion':d.group+' breeders'} · ${cash(d.cost)}`]),choices[0]?.[0])}${action('Introduce residents','stock')}<p class="meta">One breeding species per tank. Utility companions support it. Habitat requirements are shown in the Field notes.</p>${select('crop-choice','Primary plant bed',Object.entries(PLANTS).filter(([,d])=>d.phase<=state.phase).map(([k,d])=>[k,`${d.name} · ${cash(d.seed)} starter`]),t.crop)}${action('Change planted crop','plant')}<p class="meta">Changing crops collects the old bed into inventory and plants 4 biomass of the new crop.</p>${t.ready&&state.inventory.media?button('Seed with mature media',{type:'seedMedia',id:t.id}):''}</section>
  <section class="block"><p class="eyebrow">PROTECTED BY DEFAULT</p><h2>Let surplus do the work</h2>${state.unlocks.dispatcher?`${select('policy-trim','Automatic trimming',[[false,'Manual trimming'],[true,'Trim above reserve']],t.policy.trim)}${select('policy-plants','Plant surplus',[['hold','Hold for orders & cultures'],['cash','Sell surplus']],t.policy.plants)}${select('policy-fish','Mature fish',[['hold','Hold for orders / transfers'],['cash','Sell surplus immediately'],['market','Marketplace · 3-minute delivery']],t.policy.fish)}${select('policy-food','Feeding',[['balanced','Balanced food · always included'],['live','Use available live food · +25% brood']],t.policy.food)}<label class="field">Retained plant biomass<input id="reserve-value" type="number" min="4" max="${v.plantCap/1000-1}" step="1" value="${t.reserve/1000}"></label>${action('Set protected reserve','reserve')}`:'<p>After selling four juveniles, install the surplus dispatcher. It unlocks automatic trimming and sales without selling your breeders.</p>'}<p class="tradeoff">A larger plant reserve produces more growth, but leaves less space for uncollected surplus. Fish capacity is reserved from birth.</p></section></div>
  ${state.tanks.length>1?`<details class="block"><summary>Move a line or make nursery space</summary>${select('transfer-to','Destination aquarium',routeChoices.slice(1),routeChoices[1]?.[0])}<div class="actions">${action('Move mature group','transfer')}${action('Seed new breeders','seed-line')}${action('Move first fry cohort','move-fry')}</div>${state.unlocks.dispatcher?select('policy-nursery','Automatic grown-fish transfer',routeChoices,t.policy.nursery||''):''}<p class="meta">Transfers preserve real stock. The destination must be commissioned, have the right habitat, and have enough safe capacity.</p></details>`:''}
  <details class="block" open><summary>Equipment & planted habitat</summary><p class="meta">Equipment lives naturally among the plants. Upgrades change the aquarium; plants are allowed to grow around them.</p><div class="equipment-grid">${Object.entries(EQUIPMENT).filter(([,d])=>d.phase<=state.phase).map(([k,d])=>{const l=t.equipment[k],full=l===d.costs.length;return `<article class="catalog-item"><span class="eyebrow">${l?'INSTALLED · TIER '+l:'AVAILABLE'}</span><h3>${full?d.names.at(-1):d.names[l]}</h3><p>${d.note}</p>${button(full?'Fully equipped':cash(d.costs[l])+' · Install',{type:'equipment',id:t.id,key:k},full||state.cash<d.costs[l])}</article>`;}).join('')}</div></details>
  ${state.phase>=5?`<section class="block"><p class="eyebrow">DIRECTED SELECTION</p><h2>A line of your own</h2><p>Appearance ${t.traits.appearance}/2 · Reliable yield ${t.traits.yield}/2</p>${t.selection?`<p>${t.selection.trait==='appearance'?'Appearance':'Yield'} project · ${t.selection.batches}/2 supported cohorts raised.</p>`:`<div class="actions">${button('Select appearance · '+cash(3000*(t.traits.appearance+1)),{type:'selection',id:t.id,key:'appearance'},!t.breeders||t.traits.appearance>=2)}${button('Select yield · '+cash(3000*(t.traits.yield+1)),{type:'selection',id:t.id,key:'yield'},!t.breeders||t.traits.yield>=2)}</div>`}<p class="meta">Raise two cohorts born during this project with live food. Appearance adds 25% sale value per tier; reliable yield adds 15% prospective brood per tier. Keep a spare grow-out tank or a sales policy to leave room for births.</p>${button('Buy 5 infusoria · $5.00',{type:'supplies',key:'food',value:'infusoria'})}</section>`:''}
  <details class="block"><summary>Water & production diagnosis</summary><div class="water-readings"><span>Ammonia <b>${t.water.a.toFixed(2)}</b></span><span>Nitrite <b>${t.water.i.toFixed(2)}</b></span><span>Nutrients <b>${t.water.n.toFixed(2)}</b></span></div><p>${esc(v.blocker)}. Plant growth can slow when nutrients or growing room run out. Filtration converts waste; plants and water exchange export it. These are game units.</p>${button('Manual water exchange · free',{type:'water',id:t.id})}</details></div>
  <aside class="side"><section><p class="eyebrow">CHAPTER ${state.phase} OF 6</p><h2>${PHASES[state.phase-1][0]}</h2>${checklist()}</section><section><p class="eyebrow">THE ROOM AROUND IT</p><div class="room-meta"><span>Shelf space <b>${f.space} / ${f.spaceCap}</b></span><span>Power <b>${f.power} / ${f.powerCap}</b></span></div>${select('tank-choice','Add an aquarium',Object.entries(FOOTPRINTS).filter(([,d])=>d.phase<=state.phase).map(([k,d])=>[k,`${d.name} · ${cash(d.cost)}`]),'starter')}${action('Commission aquarium','buy-tank','',true)}<p class="meta">Includes a sponge and 4 hornwort biomass. Fishless check takes 90 seconds.</p>${state.unlocks.controller?action('Duplicate this tank as a template','template'):''}</section><section>${globals()}</section>${state.phase>=2?`<section><h3>Spare mature media</h3><p>${state.inventory.media} ready · $3 each · 5 minutes</p>${button('Mature a module',{type:'media'},state.cash<300)}</section>`:''}${state.cash<2000?`<section><h3>A helping hand</h3><p>If you need a fresh start, the fish store pays $1 for a one-minute shift. Your plants keep growing.</p>${button('Take a short shift',{type:'recovery'},state.jobs.some(j=>j.kind==='recovery'))}</section>`:''}<section><h3>Work in progress</h3>${queue()}</section></aside></div>`;
}
function ingredients(d){return [...Object.entries(d.fish||{}).map(([k,n])=>`${n} ${d.grade?'selected ':''}${ANIMALS[k].name}`),...Object.entries(d.plants||{}).map(([k,n])=>`${qty(n)} ${PLANTS[k].name}`),...(d.media?[`${d.media} mature media`]:[]),...Object.entries(d.food||{}).map(([k,n])=>`${n} ${CULTURES[k].name}`),...(d.parts?[`${cash(Math.max(0,d.parts-(state.inventory.frames?1800:0)))} frame & care kit${state.inventory.frames?' + 1 reclaimed frame':''}`]:[])];}
function orderCards(kind){return Object.entries(kind==='setup'?RECIPES:CONTRACTS).map(([k,d])=>{const needs=orderNeeds(state,kind,k);return `<article class="catalog-item"><span class="eyebrow">${state.phase<d.phase?'CHAPTER '+d.phase:duration(d.duration)+' · '+cash(d.price)+' DELIVERY'}</span><h2>${d.name}</h2><p>${d.note}</p><ul class="ingredients">${ingredients(d).map(x=>`<li>${x}</li>`).join('')}</ul><p class="${needs.length?'shortfall':'meta'}">${needs.length?'Waiting for '+esc(needs.join(', ')):'Everything is ready. Ingredients will be reserved.'}</p><div class="actions">${button(kind==='setup'?'Assemble & deliver':'Reserve & dispatch',{type:'order',key:kind,id:k},!!needs.length,true)}${kind==='contract'&&state.unlocks.controller?button(state.repeat.includes(k)?'Stop repeating':'Repeat when ready',{type:'repeat',key:k}):''}</div></article>`;}).join('');}
function inventory(){return `<section class="block"><h2>Unreserved inventory</h2><div class="catalog-grid">${Object.entries(PLANTS).filter(([k])=>state.inventory.plants[k]>0).map(([k,d])=>`<div><h3>${d.name} · ${qty(state.inventory.plants[k])}</h3>${button('Sell cuttings',{type:'sellPlants',key:k})}</div>`).join('')||'<p>No loose cuttings yet. Trim a tank to collect them.</p>'}</div><p class="meta">${state.inventory.media} mature media · ${state.inventory.frames} repaired frames. Fish remain in their home tanks until delivery.</p></section>`;}
function market(){return `<div class="panel-head"><div><p class="eyebrow">GOOD HOMES, REGULAR CUSTOMERS</p><h2>The local exchange</h2><p>Contracts reserve exact ingredients. Marketplace lots pay 35% more than an instant sale, after three minutes.</p></div></div><div class="tab-actions">${['contracts','marketplace'].map(k=>`<button data-market="${k}" class="${marketTab===k?'active':''}">${k==='contracts'?'Regular contracts':'Marketplace lots'}</button>`).join('')}</div>${marketTab==='contracts'?`<div class="catalog-grid">${orderCards('contract')}</div>`:`<div class="catalog-grid">${state.tanks.map(t=>`<article class="catalog-item"><h2>${esc(t.name)}</h2><p>${tankView(state,t).young} sale-ready fish · ${qty(state.inventory.plants[t.crop])} ${PLANTS[t.crop].name} in shared inventory</p><div class="actions">${button('List mature fish',{type:'market',id:t.id,key:'fish'},!tankView(state,t).young)}${button('List loose cuttings',{type:'market',id:t.id,key:'plants'},!state.inventory.plants[t.crop])}</div></article>`).join('')}</div>`}<section class="block"><h2>Dispatch queue</h2>${queue()}</section>${inventory()}<section class="block"><h2>Reclaimed aquariums</h2><p>Repair and leak-test a used frame for $10 over three minutes. Sell it for $16 or use it to replace $18 of setup parts.</p><div class="actions">${button('Repair a frame · $10',{type:'repair'},state.cash<1000)}${button('Sell repaired frame · $16',{type:'sellFrame'},!state.inventory.frames)}</div></section>`;}
function cultures(){return `<div class="panel-head"><div><p class="eyebrow">THE SMALL THINGS FEED THE SMALLER THINGS</p><h2>A living pantry</h2><p>Each vessel keeps two starter portions. Harvest its surplus, or let it flow into storage automatically.</p></div></div><div class="catalog-grid">${Object.entries(CULTURES).map(([k,d],i)=>{const c=state.cultures.find(x=>x.type===k),v=c&&cultureView(state,c);return `<article class="catalog-item"><div class="culture-art" style="--culture:${['#82955a','#b69974','#b3b69b','#d4b48a'][i]}"><span>${c?c.stock:'·'}</span></div><h2>${d.name}</h2><p>${d.note}</p><p class="meta">${d.need===500?'0.5':d.need} ${d.input} → ${d.yield} portions / ${duration(d.duration)}. Uses 1 shelf space and 1 power.</p>${c?`${progress(c.progress,d.duration,d.name+' growth')}<p>${v.blocked} · ${v.ready} harvestable</p><div class="actions">${button('Harvest culture',{type:'harvestCulture',key:k},!v.ready)}${button(c.auto?'Auto harvest: on':'Enable auto harvest',{type:'cultureAuto',key:k})}</div>`:button('Start vessel · '+cash(d.cost),{type:'culture',key:k},state.cash<d.cost,true)}<p class="meta">${state.inventory.food[k]} portions in storage</p></article>`;}).join('')}</div><section class="block"><h2>Inputs & live food</h2><p>${state.inventory.nutrients.toFixed(1)} captured nutrients · ${state.inventory.feed} culture feed · ${qty(state.inventory.plants.hornwort)} hornwort cuttings. Nutrients accumulate from your fish room.</p><div class="actions">${button('20 nutrients · $2',{type:'supplies',key:'nutrients'})}${button('10 culture feed · $2',{type:'supplies',key:'feed'})}${['daphnia','infusoria','microworms'].map(k=>button('5 '+CULTURES[k].name+' · $5',{type:'supplies',key:'food',value:k})).join('')}</div><p class="tradeoff">Live food improves prospective brood size and supports selection projects. Balanced feeding is always available if a culture is empty. A failed supply chain pauses its own output.</p></section>`;}
function finale(){if(state.phase<6)return '';if(state.finale.completedAt!==null)return `<section class="completion"><p class="eyebrow">THE INDEPENDENT FISH ROOM</p><h2>Look at what grew.</h2><p>It began with a scratched aquarium and a handful of stems. Now there are familiar customers, established lines, and complete little worlds leaving your workbench.</p><div class="numbers"><span><b>${state.tanks.length}</b> aquariums</span><span><b>${state.stats.fishSold}</b> fish rehomed</span><span><b>${state.stats.setups}</b> setups delivered</span><span><b>${state.stats.strains}</b> traits established</span></div><p>Your room keeps running. Try another species, build a riparium, or leave the plants to take their time.</p>${action('Export this room','export','',true)}</section>`;return `<section class="completion"><p class="eyebrow">YOUR FINAL PROJECT</p><h2>The independent fish room</h2><p>After beginning the project, deliver the three requested designs and three supply contracts. Then maintain a commissioned, safely stocked room for 30 productive minutes.</p>${checklist()}${progress(state.finale.progress,1800,'Independent room verification')}${state.finale.active?'<p class="meta">Verification begins after deliveries are complete. Full nurseries are safe; over-capacity or uncommissioned tanks pause the timer.</p>':button('Begin the final project',{type:'finale'},false,true)}</section>`;}
function workshop(){return `${finale()}<div class="panel-head"><div><p class="eyebrow">MADE TO THRIVE</p><h2>Complete little worlds</h2><p>Build complete setups from your own surplus. Protected breeding groups and planted reserves stay in your room.</p></div></div><div class="catalog-grid">${orderCards('setup')}</div><section class="block"><h2>Assembly & delivery</h2>${queue()}</section><div class="two-columns"><section class="block"><h2>Preparation bench</h2><p>${state.inventory.media} mature modules · ${state.inventory.frames} reclaimed frames</p><div class="actions">${button('Mature media · $3 / 5 min',{type:'media'})}${button('Repair frame · $10 / 3 min',{type:'repair'})}${state.unlocks.controller?button(state.autoMedia?'Auto media: on':'Automate spare media',{type:'automedia'}):''}</div><p class="meta">Automatic preparation keeps up to six spare media modules when funds allow.</p></section><section class="block"><h2>Coordinate the room</h2>${state.unlocks.controller?`<div class="actions">${button('Hold all surplus for orders',{type:'roomPolicy',value:'hold'})}${button('Sell all surplus',{type:'roomPolicy',value:'cash'})}</div><p class="meta">Repeat contracts reserve their next bill before instant overflow sales. Templates are available beside each aquarium.</p>`:'<p>The fish room controller unlocks room-wide policies, repeat contracts, and tank templates.</p>'}${globals()}</section></div>${inventory()}`;}
function notebook(){return `<div class="panel-head"><div><p class="eyebrow">A NATURALIST’S NOTEBOOK</p><h2>What the room has taught you</h2><p>${duration(state.time)} productive time · ${cash(state.stats.earned)} earned · ${state.stats.fishSold} fish sold · ${state.stats.contracts} contracts fulfilled</p></div></div><section class="block"><h2>How to read your room</h2><p>Plants grow from the biomass you leave rooted. Trimming collects whole biomass above a protected reserve. Sell those cuttings to finance your first filter and breeding group.</p><p>Breeders stay protected. Their offspring reserve their full adult space from birth, mature over time, and become eligible for sale, transfer or orders. When a nursery fills, new births wait; fish never die while you are away.</p><p>Each installed tank has one breeding species and one primary plant crop. Different habitats unlock different animals. A contract holds its exact stock until delivery; canceling returns all undelivered ingredients.</p><p>Automatic instant sales honor the next bill of repeating contracts. Marketplace policies list whole available lots; use Hold while saving stock for setups or selection. All rates and water readings are game abstractions.</p></section><details class="block" open><summary>Animals · ${Object.keys(state.stats.bred).length} breeding lines raised</summary><div class="catalog-grid">${Object.entries(ANIMALS).map(([k,d])=>`<article><h3>${d.name} ${state.stats.bred[k]?'✓':''}</h3><p>${d.note}</p><p class="meta">Chapter ${d.phase} · ${d.utility?'Support animal':`${d.group} founders · up to ${d.batch} offspring every ${duration(d.pulse)} · mature in ${duration(d.mature)}`} · ${cash(d.price)} ${d.utility?'reference value':'base juvenile value'}</p></article>`).join('')}</div></details><details class="block"><summary>Plant crops · ${Object.keys(state.stats.cropsSold).length} sold</summary><div class="catalog-grid">${Object.entries(PLANTS).map(([k,d])=>`<article><h3>${d.name} ${state.stats.cropsSold[k]?'✓':''}</h3><p>${d.note}</p><p class="meta">Chapter ${d.phase} · ${cash(d.price)} / biomass · ${Math.round(d.rate*100)}% potential growth per minute</p></article>`).join('')}</div></details><section class="block"><h2>Chapters</h2>${PHASES.map(([title,note],i)=>`<p><strong>${i<state.phase?'✓':'○'} ${i+1}. ${title}</strong> — ${note}</p>`).join('')}</section><section class="block"><h2>Room journal</h2><ol class="history">${[...state.history].reverse().map(h=>`<li><time>${duration(h.at)}</time> ${esc(h.text)}</li>`).join('')}</ol></section>`;}
function settings(){return `<div class="panel-head"><div><p class="eyebrow">MAKE YOURSELF AT HOME</p><h2>Room settings</h2></div></div><div class="settings-grid"><section class="block"><h2>Time & comfort</h2>${select('setting-motion','Aquarium motion',[[true,'Gentle movement'],[false,'Still illustration']],state.settings.motion)}${select('setting-sound','Action tones',[[false,'Quiet'],[true,'Soft tones']],state.settings.sound)}${select('setting-textSize','Reading size',[[1,'Standard'],[1.15,'Larger'],[1.3,'Largest']],state.settings.textSize)}${select('speed','While this tab is open',[[1,'Real time · 1×'],[5,'Relaxed fast-forward · 5×'],[20,'Explore faster · 20×']],speed)}<p class="meta">Fast-forward is a play preference; it uses the same simulation. Away time runs at 1×, capped at 24 hours. Pause stops both online and away production. Speed resets to 1× when you reopen.</p>${button(state.paused?'Resume production':'Pause production',{type:'pause'})}</section><section class="block"><h2>Your next intention</h2><label class="field">A note beside the aquarium<input id="personal-goal" maxlength="160" value="${esc(state.goal||'')}" placeholder="Save a planted nano for my first customer"></label>${action('Pin this intention','pin-goal')} ${button('Use chapter guidance',{type:'goal',value:null})}</section><section class="block"><h2>Keep your room</h2><p>Saves stay in this browser. A previous valid save is retained as a backup. Export a copy before changing browsers or clearing site data.</p><div class="actions">${action('Export campaign','export','',true)}${action('Import campaign','import')}${action('Paste save text','paste-import')}${action('Save now','save')}</div>${store.blockedSave?action('Save recovered room','recover'):''}${store.readOnly?`<p class="shortfall">Another tab owns this room. This tab is read-only.</p>${action('Take over this room','takeover')}`:''}<p class="meta">Campaign saves are validated before import. The old one-tank demo has a different economy and stays separate.</p></section><section class="block"><h2>A fresh windowsill</h2><p>Start the campaign again in this browser. You can export the current room first.</p>${action('Start a new room…','new-game')}</section></div>`;}
function render(force=true){lastRender=Date.now();const active=document.activeElement;if(!force&&active&&['INPUT','SELECT','TEXTAREA'].includes(active.tagName))return;const focusId=active?.id;const focusData=active?.tagName==='BUTTON'?['command','action','tank','nav','market'].map(k=>[k,active.dataset[k]]).find(([,v])=>v!==undefined):null;const focusSummary=active?.tagName==='SUMMARY'?active.textContent:null;const openDetails=new Map([...document.querySelectorAll('#content details')].map(d=>[d.querySelector('summary')?.textContent,d.open]));
  const scrollPosition={left:window.scrollX,top:window.scrollY,behavior:'instant'};
  $('cash').textContent=cash(state.cash);$('pause').textContent=state.paused?'Resume':'Pause';$('chapter-label').textContent=`CHAPTER ${String(state.phase).padStart(2,'0')} · ${PHASES[state.phase-1][0].toUpperCase()}`;$('chapter-title').textContent=state.finale.completedAt!==null?'Look at what grew.':['Small things, growing.','A little more room.','Everything feeds something.','Made to thrive.','A line of your own.','A room that keeps its promises.'][state.phase-1];$('goal').textContent=state.goal||goal(state);
  document.body.classList.toggle('no-motion',!state.settings.motion);document.body.classList.toggle('paused',state.paused);document.documentElement.style.fontSize=16*state.settings.textSize+'px';
  if(!busy){if(store.readOnly)notice('This room is running in another tab. View it here, or take over in Settings.',true);else if(store.error)notice(store.error,true);else if(state.paused)notice('Production is paused, including time away. Resume whenever you are ready.');else notice('');}
  const navs=[['room','Aquariums',1],['market','Exchange',2],['cultures','Cultures',3],['workshop','Workshop',4],['notebook','Field notes',1],['settings','Settings',1]];
  const navigationMarkup=navs.map(([k,label,p])=>`<button data-nav="${k}" aria-current="${tab===k?'page':'false'}" ${state.phase<p?'disabled':''}>${label}${state.phase<p?` <small>Ch. ${p}</small>`:''}</button>`).join('');
  if(navKey!==state.phase+tab){$('navigation').innerHTML=navigationMarkup;navKey=state.phase+tab;}
  // Build the complete view off-document so the live page never has an empty
  // aquarium or temporarily collapsed panels during its once-per-second refresh.
  const nextView=document.createElement('template');
  nextView.innerHTML=({room,market,cultures,workshop,notebook,settings}[tab]||room)();
  nextView.content.querySelectorAll('details').forEach(d=>{const key=d.querySelector('summary')?.textContent;if(openDetails.has(key))d.open=openDetails.get(key);});
  if(tab==='room'){const t=tankById(state,selected),v=tankView(state,t);const key=JSON.stringify([t.id,!!t.ready,t.crop,Math.floor(t.biomass/1000),t.equipment,t.species,t.breeders,t.young,t.cohorts.map(c=>[c.count,c.grade]),v.promised,t.companions,t.traits,state.unlocks.controller]);const mount=nextView.content.querySelector('#tank-art');if(key===artKey&&artElement){mount.replaceWith(artElement);}else{renderAquarium(mount,state,t,v);artKey=key;artElement=mount;}}
  $('content').replaceChildren(nextView.content);
  if(focusId)$(focusId)?.focus({preventScroll:true});else if(focusData){const [key,value]=focusData;[...document.querySelectorAll('button')].find(b=>b.dataset[key]===value)?.focus({preventScroll:true});}else if(focusSummary){[...document.querySelectorAll('summary')].find(e=>e.textContent===focusSummary)?.focus({preventScroll:true});}
  // Restore synchronously, before painting; a delayed scroll would fight input.
  // The browser clamps this naturally if a newly selected page is shorter.
  window.scrollTo(scrollPosition);
}
function modal(html){$('modal-content').innerHTML=html;$('modal').showModal();}
function download(){const blob=new Blob([encodeSave(state)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`little-current-chapter-${state.phase}-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Campaign exported. Keep that file somewhere safe.');}
document.addEventListener('click',async event=>{const target=event.target.closest('button');if(!target)return;if(target.dataset.command){dispatch(JSON.parse(target.dataset.command));return;}if(target.dataset.nav){tab=target.dataset.nav;render();return;}if(target.dataset.tank){selected=target.dataset.tank;render();return;}if(target.dataset.market){marketTab=target.dataset.market;render();return;}const t=tankById(state,selected);switch(target.dataset.action){
  case 'reconfigure':modal(`<h2>Make room for another line</h2><p>Rehoming sells mature juveniles normally, returns half the founders’ purchase value, and donates all growing fry and utility companions. It ends this tank’s selection project and clears its strain traits. Reserved orders must be delivered or canceled first.</p>${button('Rehome this tank’s livestock',{type:'rehome',id:selected})}<p style="margin-top:18px">Once empty of livestock, you can retire the tank. This collects its plants, returns half the frame and equipment purchase value, and frees its space and power. Keep at least one aquarium.</p>${button('Retire empty aquarium',{type:'retireTank',id:selected})}`);break;
  case 'stock':dispatch({type:'stock',id:selected,key:$('stock-choice').value});break;
  case 'plant':dispatch({type:'plant',id:selected,key:$('crop-choice').value});break;
  case 'buy-tank':dispatch({type:'buyTank',key:$('tank-choice').value});break;
  case 'reserve':dispatch({type:'reserve',id:selected,value:Number($('reserve-value').value)*1000});break;
  case 'transfer':case 'seed-line':dispatch({type:'transfer',id:selected,to:$('transfer-to').value,value:target.dataset.action==='seed-line'});break;
  case 'move-fry':dispatch({type:'moveFry',id:selected,to:$('transfer-to').value});break;
  case 'template':modal(`<h2>Repeat ${esc(t.name)}</h2><p>This template costs ${cash(templatePrice(t))} and one mature media module. It buys a fresh tank, this crop’s starter, installed equipment and one founder group. It uses one mature media module. Stock and selection traits in the original tank stay there.</p>${button('Purchase configured tank',{type:'template',id:selected})}`);break;
  case 'rename':modal(`<h2>Name this aquarium</h2><label class="field">Aquarium name<input id="rename-value" maxlength="40" value="${esc(t.name)}"></label>${action('Save name','save-name')}`);break;
  case 'save-name':dispatch({type:'rename',id:selected,value:$('rename-value').value});$('modal').close();break;
  case 'pin-goal':dispatch({type:'goal',value:$('personal-goal').value||null});break;
  case 'save':save();toast(store.error||'Your room is saved.');break;
  case 'recover':save(true);render();break;
  case 'export':download();break;
  case 'import':$('import-file').click();break;
  case 'paste-import':modal('<h2>Paste a campaign save</h2><label class="field">Save JSON<textarea id="paste-save" rows="8" spellcheck="false" style="width:100%;font-size:12px"></textarea></label>'+action('Check pasted save','check-paste'));break;
  case 'check-paste':previewImport($('paste-save').value);break;
  case 'takeover':{const fresh=store.load();store.claim(true);if(fresh){state=fresh.state;selected=state.tanks[0].id;await catchUp(fresh.credited);}lastWall=Date.now();render();break;}
  case 'new-game':modal(`<h2>A fresh windowsill?</h2><p>This replaces the campaign saved in this browser. Export a copy if you want to return to this room.</p><div class="actions">${action('Export current room','export')}${action('Start fresh','confirm-new')}</div>`);break;
  case 'confirm-new':if(store.readOnly){toast('Take over the room in Settings first.');break;}state=initialState();selected='t1';tab='room';speed=1;lastWall=Date.now();store.save(state,lastWall,true);$('modal').close();render();break;
  case 'confirm-import':if(store.readOnly){toast('Take over the room in Settings first.');break;}if(pendingImport){state=pendingImport.state;selected=state.tanks[0].id;pendingImport=null;tab='room';store.save(state,Date.now(),true);$('modal').close();lastWall=Date.now();render();toast('Campaign imported.');}break;
}});
document.addEventListener('change',event=>{const {id,value}=event.target;if(id.startsWith('policy-')){const key=id.slice(7);dispatch({type:'policy',id:selected,key,value:key==='trim'?value==='true':key==='nursery'?value||null:value});}else if(id.startsWith('setting-')){const key=id.slice(8);dispatch({type:'settings',key,value:key==='textSize'?Number(value):value==='true'});}else if(id==='speed'){speed=Number(value);lastWall=Date.now();toast(`Open-tab production set to ${speed}×.`);}});
let pendingImport=null;
function previewImport(raw){try{pendingImport=decodeSave(raw,Date.now(),false);$('modal-content').innerHTML='<h2>Import this room?</h2><p>Chapter '+pendingImport.state.phase+' · '+pendingImport.state.tanks.length+' aquariums · '+cash(pendingImport.state.cash)+'. This replaces the browser campaign with the exported snapshot. No away time is added.</p><div class="actions">'+action('Export current room','export')+action('Import this campaign','confirm-import','',true)+'</div>';if(!$('modal').open)$('modal').showModal();}catch(error){pendingImport=null;toast('Import rejected: '+error.message);}}

$('import-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>2_000_000)throw new Error('This file is too large.');pendingImport=decodeSave(await file.text(),Date.now(),false);modal(`<h2>Import this room?</h2><p>Chapter ${pendingImport.state.phase} · ${pendingImport.state.tanks.length} aquariums · ${cash(pendingImport.state.cash)}. This will replace the room in this browser. Import restores the exported snapshot; it does not add away time.</p><div class="actions">${action('Export current room','export')}${action('Import this campaign','confirm-import','',true)}</div>`);}catch(error){pendingImport=null;toast(`Import rejected: ${error.message}`);}});
$('pause').addEventListener('click',()=>dispatch({type:'pause'}));$('close-modal').addEventListener('click',()=>$('modal').close());
document.addEventListener('visibilitychange',()=>{if(document.hidden){save();lastWall=Date.now();}else{const elapsed=Math.max(0,(Date.now()-lastWall)/1000);lastWall=Date.now();if(!state.paused)catchUp(Math.min(elapsed,OFFLINE_CAP));}});
window.addEventListener('pagehide',()=>{save();store.release();});
window.addEventListener('storage',event=>{if(event.key?.endsWith('-writer')&&!store.owns()){store.readOnly=true;render();}if(event.key===SAVE_KEY&&store.readOnly){const fresh=store.load();if(fresh){state=fresh.state;render(false);}}});
store.heartbeat(()=>render());
try{await loadArt();}catch{notice('The aquarium illustration could not load. Reload to try again.',true);}
render();if(loaded?.credited&&!store.readOnly)await catchUp(loaded.credited);else save();lastWall=Date.now();setInterval(tick,250);
