import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,tank,act,advance,tankView,validate,encodeSave,decodeSave,held} from './engine.mjs';
import {runCampaign} from './campaign-route.mjs';
import {SaveStore,SAVE_KEY} from './persistence.mjs';
import {ANIMALS,PLANTS,CULTURES} from './content.mjs';
function command(s,c){const r=act(s,c);assert.equal(r.ok,true,r.message);return r.state;}
function breeder(){let s=initialState();s.cash=100000;s=advance(s,45);s=command(s,{type:'equipment',id:'t1',key:'sponge'});return command(s,{type:'stock',id:'t1',key:'guppy'});}
test('opening resources finance a breeding group without grants',()=>{let s=initialState();s=command(s,{type:'harvest',id:'t1'});s=command(s,{type:'sellPlants',key:'hornwort'});assert.equal(s.cash,1800);s=advance(s,180);s=command(s,{type:'harvest',id:'t1'});s=command(s,{type:'sellPlants',key:'hornwort'});s=command(s,{type:'equipment',id:'t1',key:'sponge'});s=command(s,{type:'stock',id:'t1',key:'guppy'});assert.equal(s.tanks[0].breeders,4);assert.ok(s.cash>=0);validate(s);});
test('breeders remain protected; cohorts occupy adult capacity from birth',()=>{let s=breeder();s=advance(s,240);assert.equal(tankView(s,s.tanks[0]).fry,4);assert.equal(tankView(s,s.tanks[0]).load,8);assert.equal(act(s,{type:'sellFish',id:'t1'}).ok,false);s=advance(s,1200);const t=s.tanks[0];assert.equal(tankView(s,t).count,12);s=command(s,{type:'sellFish',id:'t1'});assert.equal(s.tanks[0].breeders,4);assert.equal(tankView(s,s.tanks[0]).count,4);});
test('orders reserve real stock, cancellation restores it, delivery pays once',()=>{let s=breeder();s.phase=2;s=advance(s,900);const before=structuredClone(s);s=command(s,{type:'order',key:'contract',id:'guppy'});assert.equal(held(s,'t1'),8);assert.equal(tankView(s,s.tanks[0]).count,12);assert.equal(act(s,{type:'order',key:'contract',id:'guppy'}).ok,false);s=command(s,{type:'cancel',id:s.jobs[0].id});assert.deepEqual(s.inventory,before.inventory);assert.deepEqual(s.tanks,before.tanks);s=command(s,{type:'order',key:'contract',id:'guppy'});s=advance(s,120);assert.equal(s.cash,before.cash+3400);s=advance(s,120);assert.equal(s.cash,before.cash+3400);assert.equal(s.stats.contracts,1);validate(s);});
test('failed orders and purchases are atomic',()=>{let s=breeder();s.phase=4;s.unlocks.workshop=1;s.inventory.plants.hornwort=4000;s.inventory.media=1;const before=structuredClone(s);assert.equal(act(s,{type:'order',key:'setup',id:'guppy'}).ok,false);assert.deepEqual(s,before);s.cash=0;assert.equal(act(s,{type:'equipment',id:'t1',key:'light'}).ok,false);assert.equal(s.tanks[0].equipment.light,0);});
test('sensor never exceeds the physical tank footprint',()=>{let s=breeder();s.phase=2;s=command(s,{type:'equipment',id:'t1',key:'sensor'});assert.equal(tankView(s,s.tanks[0]).capacity,12);});
test('simulation partitions and offline replay are identical',()=>{const s=breeder(),whole=advance(s,3600);let partitioned=s;for(let i=0;i<60;i++)partitioned=advance(partitioned,60);assert.deepEqual(partitioned,whole);assert.deepEqual(decodeSave(encodeSave(s,1000),3601000).state,whole);assert.deepEqual(decodeSave(encodeSave(s,1000),0).state,s);const paused={...s,paused:true};assert.deepEqual(decodeSave(encodeSave(paused,1000),99999999).state,paused);assert.equal(decodeSave(encodeSave(s,0),999999999,false).credited,86400);});
test('selection credits only cohorts from the current project',()=>{let s=breeder();s.phase=5;s.inventory.food.infusoria=50;s=command(s,{type:'selection',id:'t1',key:'appearance'});const oldKey=s.tanks[0].selection.key;s=advance(s,480);s=command(s,{type:'sellFish',id:'t1'});s=advance(s,240);assert.equal(s.tanks[0].traits.appearance,1);s=command(s,{type:'selection',id:'t1',key:'yield'});assert.notEqual(s.tanks[0].selection.key,oldKey);s=command(s,{type:'sellFish',id:'t1'});s=advance(s,240);assert.equal(s.tanks[0].selection.batches,0);validate(s);});
test('final verification requires elapsed production, not button clicks',()=>{let s=initialState();s.phase=6;s.tanks[0].ready=0;s.finale={active:true,delivered:['guppy','planted','breeder'],supply:3,progress:1799,completedAt:null};for(let i=0;i<3;i++)s=command(s,{type:'settings',key:'motion',value:false});assert.equal(s.finale.progress,1799);assert.equal(s.finale.completedAt,null);s=advance(s,1);assert.equal(s.finale.progress,1800);assert.equal(s.finale.completedAt,1);assert.equal(s.history.filter(h=>h.text.startsWith('The Independent Fish Room is complete')).length,1);});
test('invalid imported saves are rejected before simulation',()=>{for(const mutate of [s=>delete s.tanks[0].ready,s=>delete s.stats.fishSold,s=>s.cash=-1,s=>s.tanks[0].policy.nursery='missing',s=>s.tanks[0].biomass=999999,s=>s.inventory.food.infusoria=NaN,s=>s.tanks[0].equipment.sponge=100]){const s=initialState();mutate(s);assert.throws(()=>validate(s));}assert.throws(()=>decodeSave('{"schema":"other"}'));});
test('imported identifiers must be authored content, not inherited object properties',()=>{for(const mutate of [s=>s.tanks[0].crop='constructor',s=>s.tanks[0].species='toString',s=>s.tanks[0].footprint='constructor',s=>s.repeat=['constructor'],s=>s.finale.delivered=['toString']]){const s=initialState();mutate(s);assert.throws(()=>validate(s));}});
test('the complete six-chapter campaign is reachable using legal player actions',()=>{const result=runCampaign();assert.equal(result.state.phase,6);assert.ok(result.state.finale.completedAt>0);assert.equal(result.milestones.length,6);assert.ok(result.commands>100);validate(result.state);});
test('reconfiguration clears a line without escaping reserved orders',()=>{let s=breeder();s.phase=2;s=advance(s,900);s=command(s,{type:'order',key:'contract',id:'guppy'});assert.equal(act(s,{type:'rehome',id:'t1'}).ok,false);s=command(s,{type:'cancel',id:s.jobs[0].id});s=command(s,{type:'rehome',id:'t1'});assert.equal(s.tanks[0].species,null);s=command(s,{type:'stock',id:'t1',key:'shrimp'});assert.equal(s.tanks[0].species,'shrimp');assert.equal(act(s,{type:'retireTank',id:'t1'}).ok,false);validate(s);});
test('transfers preserve stock and templates purchase fresh production',()=>{let s=breeder();s.phase=5;s.unlocks.room=1;s.unlocks.controller=1;s.inventory.media=1;s=advance(s,900);s=command(s,{type:'buyTank',key:'long'});const id=s.tanks.at(-1).id;s=advance(s,90);s=command(s,{type:'transfer',id:'t1',to:id,value:true});assert.equal(s.tanks[0].young[0],4);assert.equal(s.tanks[1].breeders,4);const oldCash=s.cash;s=command(s,{type:'template',id});assert.ok(s.cash<oldCash);assert.equal(s.tanks[2].breeders,4);assert.equal(s.tanks[2].ready,10);assert.equal(s.inventory.media,0);assert.equal(s.tanks[0].breeders,4);validate(s);});
test('culture starters survive missing inputs and automatic harvest',()=>{let s=initialState();s.phase=3;s.cash=10000;s.unlocks.rack=1;s.unlocks.circuit=1;s=command(s,{type:'culture',key:'greenwater'});s=command(s,{type:'cultureAuto',key:'greenwater'});s.inventory.nutrients=0;s=advance(s,600);assert.equal(s.cultures[0].stock,2);assert.equal(s.stats.cultureProduced,0);s=command(s,{type:'supplies',key:'nutrients'});s=advance(s,121);assert.equal(s.inventory.food.greenwater,4);assert.equal(s.cultures[0].stock,2);validate(s);});
test('repeating contracts keep their next bill ahead of cash overflow',()=>{let s=initialState();s.phase=4;s.unlocks.controller=1;s.unlocks.dispatcher=1;s.inventory.plants.hornwort=18000;s.tanks[0].policy.plants='cash';s=command(s,{type:'repeat',key:'plants'});s=advance(s,1);assert.equal(s.inventory.plants.hornwort,6000);assert.equal(s.jobs[0].escrow.plants.hornwort,6000);assert.equal(s.cash,2400);s=advance(s,120);assert.equal(s.stats.contracts,1);assert.equal(s.jobs.filter(j=>j.kind==='contract').length,1);validate(s);});
test('setup cancellation returns every ingredient and parts payment',()=>{let s=breeder();s.phase=4;s.unlocks.rack=1;s.unlocks.workshop=1;s.inventory.media=1;s.inventory.frames=1;s.inventory.plants.hornwort=4000;s=advance(s,900);const before=structuredClone(s);s=command(s,{type:'order',key:'setup',id:'guppy'});assert.equal(s.cash,before.cash-800);assert.equal(s.inventory.frames,0);s=command(s,{type:'cancel',id:s.jobs[0].id});assert.deepEqual(s.inventory,before.inventory);assert.equal(s.cash,before.cash);assert.deepEqual(s.tanks,before.tanks);validate(s);});
test('a corrupted current save recovers its valid backup without overwriting it',()=>{const data=new Map(),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const a=new SaveStore(storage);a.claim();a.save(initialState(),1000);const updated=initialState();updated.cash=700;a.save(updated,2000);data.set(SAVE_KEY,'corrupted');const loaded=a.load(2000);assert.equal(loaded.state.cash,600);assert.equal(a.blockedSave,true);assert.equal(a.save(loaded.state,2000),false);assert.equal(data.get(SAVE_KEY),'corrupted');assert.equal(a.save(loaded.state,2000,true),true);a.release();});
test('only the owning tab may write a campaign',()=>{const data=new Map(),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const a=new SaveStore(storage),b=new SaveStore(storage);assert.equal(a.claim(),true);assert.equal(b.claim(),false);assert.equal(b.save(initialState()),false);assert.equal(b.claim(true),true);assert.equal(a.save(initialState()),false);assert.equal(b.save(initialState()),true);b.release();});
test('every authored breeding species reaches a mature cohort in its supported habitat',()=>{for(const [key,a]of Object.entries(ANIMALS)){if(a.utility)continue;let s=initialState();s.phase=6;s.cash=100000;s.unlocks.room=1;s.tanks=[tank('t1','display')];s.tanks[0].ready=0;s.tanks[0].equipment.sponge=3;s.tanks[0].equipment.nursery=1;s.tanks[0].equipment.cave=1;s.tanks[0].equipment.calm=1;s=command(s,{type:'stock',id:'t1',key});s=advance(s,a.pulse+a.mature+1);assert.equal(s.stats.bred[key],true,key);assert.ok(s.tanks[0].young.some(Boolean),key);validate(s);}});
test('all crops grow and every culture can produce its own surplus',()=>{for(const key of Object.keys(PLANTS)){let s=initialState();s.phase=6;s.cash=100000;s.tanks[0].equipment.light=1;if(key!=='hornwort')s=command(s,{type:'plant',id:'t1',key});const before=s.tanks[0].biomass;s=advance(s,180);assert.ok(s.tanks[0].biomass>before,key);validate(s);}for(const [key,d]of Object.entries(CULTURES)){let s=initialState();s.phase=3;s.cash=100000;s.inventory.food.greenwater=10;s.inventory.plants.hornwort=5000;s=command(s,{type:'culture',key});s=advance(s,d.duration);s=command(s,{type:'harvestCulture',key});assert.ok(s.inventory.food[key]>=4,key);assert.equal(s.cultures[0].stock,2);validate(s);}});
